### ISSUE TITLE
能帮忙看下这个报错吗...

### ISSUE THREAD

**Issue by Sinyuk7** [Chion82/WeChatMomentStat-Android#23]
问下这个错误怎么解决....
- asset下面的apk文件的干嘛的
- 我需要把它替换成手机上安装的微信版本吗
- 现在支持的最新版本是什么呢

Thanks in advanced 🌹

---

logcat:
android.database.sqlite.SQLiteException: no such table: snsExtInfo3 (code 1): , while compiling: SELECT userName FROM snsExtInfo3 WHERE ROWID=? LIMIT 1
                                                                                   at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                   at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:896)
                                                                                   at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:507)
                                                                                   at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                                   at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                                   at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                                   at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                                   at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1346)
                                                                                   at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1193)
                                                                                   at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1064)
                                                                                   at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1270)
                                                                                   at moe.chionlab.wechatmomentstat.SnsReader.getCurrentUserIdFromDatabase(SnsReader.java:59)
                                                                                   at moe.chionlab.wechatmomentstat.SnsReader.queryDatabase(SnsReader.java:49)
                                                                                   at moe.chionlab.wechatmomentstat.SnsReader.run(SnsReader.java:33)
                                                                                   at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:62)
                                                                                   at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:53)
                                                                                   at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                   at java.lang.Thread.run(Thread.java:818)

**Comment by Chion82** [comment]
请更新微信版本到6.5.4。
assets下的apk是这个工具所使用的二进制数据parser，可以不用理会。
