### ISSUE TITLE
倒数据失败

### ISSUE THREAD

**Issue by FrankAblert** [Chion82/WeChatMomentStat-Android#3]
获取啦root权，提示查询微信缓存失败，请获取
root权。。。。

**Comment by Chion82** [comment]
请检查在外部存储的`WeChatMomentStat`目录中是否有`SnsMicroMsg.db`这个文件。如果没有这个文件，说明微信数据库文件拷贝失败，请尝试手动将`/data/data/com.tencent.mm/MicroMsg/XXX/SnsMicroMsg.db`（其中XXX为一串hash值，每台设备上都不一样）复制到`/sdcard/WeChatMomentStat/SnsMicroMsg.db`

**Comment by MacLeek** [comment]
这个问题我也遇到，用的是nexus5 os5.1.1，Environment.getExternalStorageDirectory()返回/storage/emulated/0，这个目录对当前的程序来说好像不可用，换成这个Environment.getLegacyExternalStorageDirectory (/storage/emulated/legacy)倒是可以。

**Comment by Chion82** [comment]
@MacLeek 如果用`Environment.getLegacyExternalStorageDirectory()`的话，在全部设备上都能得到可用的目录吗？

**Comment by MacLeek** [comment]
@Chion82 这个我就不清楚了，不是搞android的 :(

**Comment by bluebad** [comment]
复制了那个文件，但仍旧提示“查询缓存失败”，手机是已经ROOT过的。
复制之后，再使用“运行”，发现WeChatMomentStat目录中会多出一个json文件，但是是空的。
复制文件之后的运行，会有几十秒才会结束，貌似在分析db文件？
系统是4.1.2

**Comment by bluebad** [comment]
复制之后，再使用“运行”，发现WeChatMomentStat目录中会多出一个json文件，但是是空的

**Comment by Chion82** [comment]
@bluebad 请提供logcat记录

**Comment by sicklife** [comment]
> 请检查在外部存储的WeChatMomentStat目录中是否有SnsMicroMsg.db这个文件。如果没有这个文件，说明微信数据库文件拷贝失败，请尝试手动将/data/data/com.tencent.mm/MicroMsg/XXX/SnsMicroMsg.db（其中XXX为一串hash值，每台设备上都不一样）复制到/sdcard/WeChatMomentStat/SnsMicroMsg.db

没有找到/data/data/com.tencent.mm/MicroMsg/XXX/SnsMicroMsg.db 

环境：
小米4c, MIUI8.6.9.1开发版，
微信：6.3.23

logcat:
`10-17 10:43:16.478 29269-29302/? D/vip_debug: TaskModel.onAppChangeEvent, packageName = moe.chionlab.wechatmomentstat, task.name = (P:29269)(T:pool-2-thread-1)(C:TaskModel)at (TaskModel.java:283)
10-17 10:43:16.488 29304-29304/? D/MarketLocalAppManager: local app moe.chionlab.wechatmomentstat added
10-17 10:43:16.738 13190-29409/? I/themeservice: saving icon for /data/data/com.miui.home/cache/moe.chionlab.wechatmomentstat.png
10-17 10:43:16.738 29431-29454/? I/themeservice: saving icon remotely(13190) for /data/data/com.miui.home/cache/moe.chionlab.wechatmomentstat.png ALLOW: true
10-17 10:43:16.878 1060-3624/? W/BroadcastQueueInjector: Unable to launch app com.sina.weibo/10108 for broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:moe.chionlab.wechatmomentstat flg=0x4000010 (has extras) }: process is not permitted to  auto start
10-17 10:43:17.498 16005-16026/? I/AD-PLUGIN-SystemAdController: offline package moe.chionlab.wechatmomentstat
10-17 10:43:17.498 16005-16026/? I/AD-PLUGIN-SystemAdController: requestSplash, package:moe.chionlab.wechatmomentstat, intent:Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=moe.chionlab.wechatmomentstat/.gui.MainActivity }, showing:false
10-17 10:43:17.498 16005-16026/? I/AD-PLUGIN-SplashConfigCache: packageName:moe.chionlab.wechatmomentstat, showInterval:600000
10-17 10:43:17.498 16005-16026/? I/AD-PLUGIN-SystemAdController: isAppSplash intent:Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=moe.chionlab.wechatmomentstat/.gui.MainActivity } aInfo:ActivityInfo{2e1d6c22 moe.chionlab.wechatmomentstat.gui.MainActivity} showType
10-17 10:43:17.508 16005-16026/? I/AD-PLUGIN-SystemAdController: slogan is not ready, package:moe.chionlab.wechatmomentstat, url:null
10-17 10:43:17.508 1060-5067/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=moe.chionlab.wechatmomentstat/.gui.MainActivity} from uid 2000 on display 0
10-17 10:43:17.508 16005-16026/? I/AD-PLUGIN-SystemAdController: requestSplashScreen duration:7, package:moe.chionlab.wechatmomentstat
10-17 10:43:17.528 1060-5067/? V/WindowManager: addAppToken: AppWindowToken{1b4cd727 token=Token{87855e6 ActivityRecord{3201ac41 u0 moe.chionlab.wechatmomentstat/.gui.MainActivity t383}}} to stack=1 task=383 at 0
10-17 10:43:17.598 1060-4931/? I/ActivityManager: Start proc 29540:moe.chionlab.wechatmomentstat/u0a135 for activity moe.chionlab.wechatmomentstat/.gui.MainActivity
10-17 10:43:17.608 1060-3629/? V/WindowManager: Adding window Window{207e433b u0 Starting moe.chionlab.wechatmomentstat} at 5 of 12 (after Window{2f7db47a u0 com.tencent.mm/com.tencent.mm.ui.LauncherUI})
10-17 10:43:17.658 10751-10789/? D/PowerKeeperEventLogManager: notifyForegroundCompomentChanged ComponentInfo{moe.chionlab.wechatmomentstat/moe.chionlab.wechatmomentstat.gui.MainActivity}
10-17 10:43:17.668 5393-5751/? D/WtProcessController: set foreground process size 1 pid:29540pacakgeName:moe.chionlab.wechatmomentstat
10-17 10:43:17.678 10751-10804/? D/NetworkController: send broadcast android.net.conn.CONNECTIVITY_CHANGE to moe.chionlab.wechatmomentstat
10-17 10:43:17.958 1060-5903/? V/WindowManager: Adding window Window{18528c70 u0 moe.chionlab.wechatmomentstat/moe.chionlab.wechatmomentstat.gui.MainActivity} at 5 of 13 (before Window{207e433b u0 Starting moe.chionlab.wechatmomentstat})
10-17 10:43:18.438 1060-3629/? I/ActivityManager: Displayed moe.chionlab.wechatmomentstat/.gui.MainActivity: +874ms (total +17s825ms)
10-17 10:43:18.438 1060-3629/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{3201ac41 u0 moe.chionlab.wechatmomentstat/.gui.MainActivity t383} time:241028535
10-17 10:43:18.448 16005-16991/? I/AD-PLUGIN-SystemAdController: activityIdle:ActivityInfo{1dc596b3 moe.chionlab.wechatmomentstat.gui.MainActivity} mPendingSwitchingActivityInfo:null
10-17 10:43:18.468 13099-13099/? D/canna-debug: onStartInput-- pacakte=moe.chionlab.wechatmomentstat inputType=0 KeyboardShown=false
10-17 10:43:23.158 1060-3629/? V/WindowManager: Adding window Window{13cb88da u0 Starting com.miui.securitycenter} at 6 of 13 (after Window{18528c70 u0 moe.chionlab.wechatmomentstat/moe.chionlab.wechatmomentstat.gui.MainActivity})
10-17 10:43:23.238 5393-5751/? D/WtProcessController: packageMoveToBackground packageName:moe.chionlab.wechatmomentstat
10-17 10:44:07.088 16005-16991/? I/AD-PLUGIN-SystemAdController: offline package moe.chionlab.wechatmomentstat
10-17 10:44:07.088 16005-16991/? I/AD-PLUGIN-SystemAdController: requestSplash, package:moe.chionlab.wechatmomentstat, intent:Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=moe.chionlab.wechatmomentstat/.gui.MainActivity bnds=[825,978][1017,1170] (has extras) }, showing:false
10-17 10:44:07.088 16005-16991/? I/AD-PLUGIN-SplashConfigCache: packageName:moe.chionlab.wechatmomentstat, showInterval:600000
10-17 10:44:07.088 16005-16991/? I/AD-PLUGIN-SystemAdController: isAppSplash intent:Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=moe.chionlab.wechatmomentstat/.gui.MainActivity bnds=[825,978][1017,1170] (has extras) } aInfo:ActivityInfo{1c5ad746 moe.chionlab.wechatmomentstat.gui.MainActivity} showType
10-17 10:44:07.088 16005-16991/? I/AD-PLUGIN-SystemAdController: slogan is not ready, package:moe.chionlab.wechatmomentstat, url:null
10-17 10:44:07.088 16005-16991/? I/AD-PLUGIN-SystemAdController: requestSplashScreen duration:5, package:moe.chionlab.wechatmomentstat
10-17 10:44:07.088 1060-5903/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=moe.chionlab.wechatmomentstat/.gui.MainActivity bnds=[825,978][1017,1170] (has extras)} from uid 10019 on display 0
10-17 10:44:07.128 5393-5751/? D/WtProcessController: set foreground process size 1 pid:29540pacakgeName:moe.chionlab.wechatmomentstat
10-17 10:44:07.128 10751-10789/? D/PowerKeeperEventLogManager: notifyForegroundCompomentChanged ComponentInfo{moe.chionlab.wechatmomentstat/moe.chionlab.wechatmomentstat.gui.MainActivity}
10-17 10:44:07.188 13099-13099/? D/canna-debug: onStartInput-- pacakte=moe.chionlab.wechatmomentstat inputType=0 KeyboardShown=false
10-17 10:44:07.208 16005-31184/? I/AD-PLUGIN-SystemAdController: activityIdle:ActivityInfo{6692d07 moe.chionlab.wechatmomentstat.gui.MainActivity} mPendingSwitchingActivityInfo:null
10-17 10:44:07.488 1060-3629/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{3201ac41 u0 moe.chionlab.wechatmomentstat/.gui.MainActivity t383} time:241077583
10-17 10:44:12.228 29864-29864/? I/dex2oat: /system/bin/dex2oat --runtime-arg -classpath --runtime-arg /system/framework/XposedBridge.jar --instruction-set=arm64 --instruction-set-features=default --runtime-arg -Xnorelocate --boot-image=/system/framework/boot.art --dex-file=/storage/emulated/0/WeChatMomentStat/wechat.apk --oat-fd=35 --oat-location=/data/data/moe.chionlab.wechatmomentstat/app_outdex/wechat.dex --runtime-arg -Xms64m --runtime-arg -Xmx512m
10-17 10:44:33.648 29540-29836/? D/wechatmomentstat: Querying Sns database.
10-17 10:44:33.648 29540-29836/? E/wechatmomentstat: /storage/emulated/0
10-17 10:44:33.648 29540-29836/? E/wechatmomentstat: DB file not found
10-17 10:44:33.668 29540-29540/? E/wechatmomentstat: exception
                                                     java.lang.Exception: DB file not found
                                                         at moe.chionlab.wechatmomentstat.SnsReader.queryDatabase(SnsReader.java:49)
                                                         at moe.chionlab.wechatmomentstat.SnsReader.run(SnsReader.java:34)
                                                         at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:62)
                                                         at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:53)
                                                         at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                         at java.lang.Thread.run(Thread.java:818)`

**Comment by sicklife** [comment]
> 请检查在外部存储的WeChatMomentStat目录中是否有SnsMicroMsg.db这个文件。如果没有这个文件，说明微信数据库文件拷贝失败，请尝试手动将/data/data/com.tencent.mm/MicroMsg/XXX/SnsMicroMsg.db（其中XXX为一串hash值，每台设备上都不一样）复制到/sdcard/WeChatMomentStat/SnsMicroMsg.db

我拷贝了这个文件之后，运行程序还是报错。。。。

`10-17 11:53:27.628 8851-8851/? E/wechatmomentstat: exception
                                                   android.database.sqlite.SQLiteException: no such table: snsExtInfo2 (code 1): , while compiling: SELECT userName FROM snsExtInfo2 WHERE ROWID=? LIMIT 1
                                                       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                                                       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                       at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                       at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
                                                       at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1163)
                                                       at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1034)
                                                       at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1240)
                                                       at moe.chionlab.wechatmomentstat.SnsReader.getCurrentUserIdFromDatabase(SnsReader.java:64)
                                                       at moe.chionlab.wechatmomentstat.SnsReader.queryDatabase(SnsReader.java:54)
                                                       at moe.chionlab.wechatmomentstat.SnsReader.run(SnsReader.java:34)
                                                       at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:62)
                                                       at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:53)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                       at java.lang.Thread.run(Thread.java:818)`

**Comment by lxzliuxinzhu** [comment]
用三星Galaxy Note 2测试，WeChatMomentStat里面有SnsMicroMsg.db和wechat.ask两个文件。。也获得了root权限。支行的时候，依旧提示请获取root。再去看WeChatMomentStat里面，多了一个SnsMicroMsg.db-jouranl的文件

**Comment by Chion82** [comment]
@sicklife 最新版已解决这个问题，请下载最新release

**Comment by Chion82** [comment]
@lxzliuxinzhu 请尝试更新版本，如果仍然报错，请提供logcat的Error纪录

**Comment by lxzliuxinzhu** [comment]
数据库和微信安装包都 有。
11-23 18:56:00.100 21712-21712/? E/ClockAlarmWidget: [AlarmWidgetIdManager] getListItem() : itemIndex=0, widgetID:1
11-23 18:56:00.100 8280-8280/? D/widget: [MSC_SinaWeather_JB]>>> SM:1289 [0:0] bTCC WCV = 100
11-23 18:56:00.100 21712-21712/? E/ClockAlarmWidget: [AlarmWidgetIdManager] getListItem() : ItemIndex exceed ListItemCount. itemIndex=1
11-23 18:56:00.100 21712-21712/? E/ClockAlarmWidget: [AlarmWidgetIdManager] getListItem() : itemIndex=1, widgetID:1
11-23 18:56:00.100 8280-8280/? D/widget: [MSC_SinaWeather_JB]>>> SWC:1264 [0:0] drw 1nd Tm dt = 1856
11-23 18:56:00.120 21712-21712/? D/ClockAlarmDataProvider: getAlarm() - too many same ID alarm data. nCount: 0
11-23 18:56:00.275 2338-11228/? D/wechatmomentstat: Querying Sns database.
11-23 18:56:00.295 2338-11228/? E/SQLiteLog: (1) no such table: snsExtInfo3
11-23 18:56:00.300 2338-2338/? E/wechatmomentstat: exception
                                                   android.database.sqlite.SQLiteException: no such table: snsExtInfo3 (code 1): , while compiling: SELECT userName FROM snsExtInfo3 WHERE ROWID=? LIMIT 1
                                                       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1012)
                                                       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:623)
                                                       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                       at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                       at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
                                                       at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1161)
                                                       at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1032)
                                                       at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1238)
                                                       at moe.chionlab.wechatmomentstat.SnsReader.getCurrentUserIdFromDatabase(SnsReader.java:59)
                                                       at moe.chionlab.wechatmomentstat.SnsReader.queryDatabase(SnsReader.java:49)
                                                       at moe.chionlab.wechatmomentstat.SnsReader.run(SnsReader.java:33)
                                                       at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:62)
                                                       at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:53)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                                       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                                       at java.lang.Thread.run(Thread.java:856)

**Comment by lxzliuxinzhu** [comment]
数据库和安装包都有的
11-23 19:17:19.430 5623-5850/? E/SQLiteLog: (1) no such table: snsExtInfo3
11-23 19:17:19.430 2324-5941/? D/STATUSBAR-NotificationService: enqueueToast()
11-23 19:17:19.435 5623-5623/? E/wechatmomentstat: exception
                                                   android.database.sqlite.SQLiteException: no such table: snsExtInfo3 (code 1): , while compiling: SELECT userName FROM snsExtInfo3 WHERE ROWID=? LIMIT 1
                                                       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1012)
                                                       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:623)
                                                       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                       at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                       at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
                                                       at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1161)
                                                       at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1032)
                                                       at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1238)
                                                       at moe.chionlab.wechatmomentstat.SnsReader.getCurrentUserIdFromDatabase(SnsReader.java:59)
                                                       at moe.chionlab.wechatmomentstat.SnsReader.queryDatabase(SnsReader.java:49)
                                                       at moe.chionlab.wechatmomentstat.SnsReader.run(SnsReader.java:33)
                                                       at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:62)
                                                       at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:53)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                                       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                                       at java.lang.Thread.run(Thread.java:856)

**Comment by Chion82** [comment]
@lxzliuxinzhu 数据库表格式有问题。可以上传一份`SnsMicroMsg.db`样例吗？如果不希望泄漏数据的话可以临时注册个新号

**Comment by lxzliuxinzhu** [comment]
这边发数据库压缩包，试了几次都不行。没办法，最后发你tech@chionlab.moe这个邮箱了。。

**Comment by Chion82** [comment]
@lxzliuxinzhu 你发的数据库是旧版微信的格式，应该使用[旧版的工具](https://github.com/Chion82/WeChatMomentStat-Android/releases/tag/v0.0.1-beta.2)）

**Comment by lxzliuxinzhu** [comment]
现在有一个问题，在WeChatMomentStat目录下面没有数据库的情况下，手动复制数据过来后，刷新朋友圈消息，数据不会更新。是权限的问题吗？

**Comment by qinst64** [comment]
尝试尝试了手机和平板（均已root，android 6.0），微信版本6.3.31以及6.3.13，都不work，提示没有root。软件压根就没有在sdcard上新建WeChatMomentStat文件夹。我手动新建文件夹并把SnsMicroMsg.db拷贝过去，一样的错误提示。
@Chion82 不是很明白手动拷贝的意图？软件是先读取哪个SnsMicroMsg.db呢，如果同时存在那读取哪个？

**Comment by liulinbin** [comment]
@Chion82 是否能改进优化一下，可以把JSON数据POST提交到某个网址，或者发到邮箱？

**Comment by grewumi** [comment]
@FrankAblert 夜神安卓模拟器可以用，我也是用手机失败了

**Comment by lxzliuxinzhu** [comment]
之前还是好了，今天测试突然又不行了，不是搞java的，麻烦看下这个问题。百度了一下，好像是没有权限
02-04 12:27:20.468 26133-26133/? E/wechatmomentstat: exception
                                                     java.lang.reflect.InvocationTargetException
                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                         at moe.chionlab.wechatmomentstat.Parser.parseSnsDetailFromBin(Parser.java:37)
                                                         at moe.chionlab.wechatmomentstat.Parser.parseSnsAllFromBin(Parser.java:27)
                                                         at moe.chionlab.wechatmomentstat.SnsReader.addSnsInfoFromCursor(SnsReader.java:70)
                                                         at moe.chionlab.wechatmomentstat.SnsReader.queryDatabase(SnsReader.java:52)
                                                         at moe.chionlab.wechatmomentstat.SnsReader.run(SnsReader.java:33)
                                                         at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:62)
                                                         at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:53)
                                                         at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                         at java.lang.Thread.run(Thread.java:841)
                                                      Caused by: java.lang.NullPointerException
                                                         at a.a.a.a.a.<init>(SourceFile:24)
                                                         at com.tencent.mm.protocal.b.atp.a(SourceFile:128)
                                                         at com.tencent.mm.at.a.am(SourceFile:52)
                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                         at java.lang.reflect.Method.invoke(Method.java:515) 
                                                         at moe.chionlab.wechatmomentstat.Parser.parseSnsDetailFromBin(Parser.java:37) 
                                                         at moe.chionlab.wechatmomentstat.Parser.parseSnsAllFromBin(Parser.java:27) 
                                                         at moe.chionlab.wechatmomentstat.SnsReader.addSnsInfoFromCursor(SnsReader.java:70) 
                                                         at moe.chionlab.wechatmomentstat.SnsReader.queryDatabase(SnsReader.java:52) 
                                                         at moe.chionlab.wechatmomentstat.SnsReader.run(SnsReader.java:33) 
                                                         at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:62) 
                                                         at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:53) 
                                                         at android.os.AsyncTask$2.call(AsyncTask.java:288) 
                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                         at java.lang.Thread.run(Thread.java:841)

**Comment by zfk513** [comment]
微信的文件夹里面找不到 SnsMicroMsg.db 了呀  好像很早就是sns文件夹了  ……肿么办
