### ISSUE TITLE
Window is full: requested allocation 818 bytes, free space 452 bytes, window size 2097152 bytes

### ISSUE THREAD

**Issue by dknightlx** [Chion82/WeChatMomentStat-Android#4]
`05-05 09:56:35.774 17332-17550/moe.chionlab.wechatmomentstat I/art: Alloc concurrent mark sweep GC freed 11(352B) AllocSpace objects, 0(0B) LOS objects, 1% free, 200MB/204MB, paused 1.303ms total 222.545ms
05-05 09:56:35.788 17332-17550/moe.chionlab.wechatmomentstat E/art: Throwing OutOfMemoryError "Failed to allocate a 82424620 byte allocation with 4194208 free bytes and 55MB until OOM"
05-05 09:56:35.798 17332-17550/moe.chionlab.wechatmomentstat I/art: Alloc sticky concurrent mark sweep GC freed 5(416B) AllocSpace objects, 0(0B) LOS objects, 0% free, 200MB/202MB, paused 1.627ms total 8.890ms
05-05 09:56:36.024 17332-17550/moe.chionlab.wechatmomentstat I/art: Alloc partial concurrent mark sweep GC freed 10(320B) AllocSpace objects, 0(0B) LOS objects, 1% free, 200MB/204MB, paused 1.442ms total 202.907ms
05-05 09:56:36.253 17332-17550/moe.chionlab.wechatmomentstat I/art: Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 1% free, 200MB/204MB, paused 1.525ms total 218.239ms
05-05 09:56:36.264 17332-17550/moe.chionlab.wechatmomentstat I/art: Forcing collection of SoftReferences for 78MB allocation
05-05 09:56:36.513 17332-17347/moe.chionlab.wechatmomentstat W/art: Suspending all threads took: 205.319ms
05-05 09:56:36.525 17332-17550/moe.chionlab.wechatmomentstat I/art: Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 1% free, 200MB/204MB, paused 1.700ms total 249.585ms
05-05 09:56:37.124 17332-17550/moe.chionlab.wechatmomentstat E/art: Throwing OutOfMemoryError "Failed to allocate a 82424620 byte allocation with 4194304 free bytes and 55MB until OOM"
05-05 09:56:37.144 17332-17332/moe.chionlab.wechatmomentstat E/wechatmomentstat: exception
                                                                                 java.lang.OutOfMemoryError: Failed to allocate a 82424620 byte allocation with 4194304 free bytes and 55MB until OOM
                                                                                     at java.lang.String.<init>(String.java:400)
                                                                                     at java.lang.AbstractStringBuilder.toString(AbstractStringBuilder.java:633)
                                                                                     at java.lang.StringBuilder.toString(StringBuilder.java:663)
                                                                                     at org.json.JSONStringer.toString(JSONStringer.java:430)
                                                                                     at org.json.JSONArray.toString(JSONArray.java:586)
                                                                                     at moe.chionlab.wechatmomentstat.Task.saveToJSONFile(Task.java:231)
                                                                                     at moe.chionlab.wechatmomentstat.SnsReader.run(SnsReader.java:34)
                                                                                     at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:62)
                                                                                     at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:53)
                                                                                     at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                     at java.lang.Thread.run(Thread.java:818)
`

现在我点击运行后出现了这个问题。应该是window is ful。是不是应该把SQLiteDatabase创建在存储卡里。我应该怎么做呢

**Comment by Chion82** [comment]
确实是需要外部存储的，例如SD卡或者手机自带的大容量存储。从log上看是不是设备的可用运行内存太小？
