### ISSUE TITLE
是不是最新的微信已经不支持？

### ISSUE THREAD

**Issue by hellojxt** [Chion82/WeChatMomentStat-Android#9]
java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.plugin.sns.f.i" on path: DexPathList[[zip file "/wechat.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
                                                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                   at moe.chionlab.wechatmomentstat.Task.initSnsReader(Task.java:151)
                                                                                   at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:61)
                                                                                   at moe.chionlab.wechatmomentstat.gui.MainActivity$RunningTask.doInBackground(MainActivity.java:54)
                                                                                   at android.os.AsyncTask$2.call(AsyncTask.java:307)
                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                   at java.lang.Thread.run(Thread.java:833)

**Comment by Chion82** [comment]
最新版微信一直都是支持的。
请检查外部存储目录(一般是`/sdcard`)下是否有`WeChatMomentStat`目录，以及该目录下是否有自动释放的`wechat.apk`
另外请在真实手机环境中测试，AVD环境下会有该异常

**Comment by hellojxt** [comment]
@Chion82 我也发现我的手机的Environment.getExternalStorageDirectory()中没有WeChatMomentStat目录，也没有读写的权限，我把EXT_DIR 改为"/data/data/moe.chionlab.wechatmomentstat/WeChatMomentStat"后程序正常

**Comment by Chion82** [comment]
谢谢提醒
可能部分机型确实会有这个问题，以后有空我会跟进一下

**Comment by wowenwen** [comment]
模拟器没法运行是吧？

**Comment by Chion82** [comment]
@wowenwen 测试过avd模拟器不能运行，其他模拟器未知

**Comment by YunSpider** [comment]
请问一下，json里面的图片怎么保存到本地？有的是通过拍照的形式发表的心情，这种图片获取不到。第三方网站里面的图片可以获取到

**Comment by davidblus** [comment]
经过实测，夜神模拟器5.0.0.0，微信版本6.3.13，此程序第一版WeChatMomentStat-0.0.1-beta.2.apk ，可以跑一次，只成功了一次，后面就一直失败了。
